/* hpsort.f -- translated by f2c (version 12.02.01).
   You must link the resulting object file with libf2c:
	on Microsoft Windows system, link with libf2c.lib;
	on Linux or Unix systems, link with .../path/to/libf2c.a -lm
	or, if you install libf2c.a in a standard place, with -lf2c -lm
	-- in that order, at the end of the command line, as in
		cc *.o -lf2c -lm
	Source for libf2c is in /netlib/f2c/libf2c.zip, e.g.,

		http://www.netlib.org/f2c/libf2c.zip
*/

#include <stdlib.h> /* For exit() */
#include <f2c.h>

/* Table of constant values */

static integer c__1 = 1;

/* DECK HPSORT */
/* Subroutine */ int hpsort_(char *hx, integer *n, integer *strbeg, integer *
	strend, integer *iperm, integer *kflag, char *work, integer *ier, 
	ftnlen hx_len, ftnlen work_len)
{
    /* System generated locals */
    integer i__1, i__2;

    /* Local variables */
    static integer i__, j, k, l, m;
    static real r__;
    static integer ij, il[21], kk, lm, ir, nn, iu[21], nn2, lmt, indx, indx0, 
	    istrt;
    extern /* Subroutine */ int xermsg_(char *, char *, char *, integer *, 
	    integer *, ftnlen, ftnlen, ftnlen);

/* ***BEGIN PROLOGUE  HPSORT */
/* ***PURPOSE  Return the permutation vector generated by sorting a */
/*            substring within a character array and, optionally, */
/*            rearrange the elements of the array.  The array may be */
/*            sorted in forward or reverse lexicographical order.  A */
/*            slightly modified quicksort algorithm is used. */
/* ***LIBRARY   SLATEC */
/* ***CATEGORY  N6A1C, N6A2C */
/* ***TYPE      CHARACTER (SPSORT-S, DPSORT-D, IPSORT-I, HPSORT-H) */
/* ***KEYWORDS  PASSIVE SORTING, SINGLETON QUICKSORT, SORT, STRING SORTING */
/* ***AUTHOR  Jones, R. E., (SNLA) */
/*           Rhoads, G. S., (NBS) */
/*           Sullivan, F. E., (NBS) */
/*           Wisniewski, J. A., (SNLA) */
/* ***DESCRIPTION */

/*   HPSORT returns the permutation vector IPERM generated by sorting */
/*   the substrings beginning with the character STRBEG and ending with */
/*   the character STREND within the strings in array HX and, optionally, */
/*   rearranges the strings in HX.   HX may be sorted in increasing or */
/*   decreasing lexicographical order.  A slightly modified quicksort */
/*   algorithm is used. */

/*   IPERM is such that HX(IPERM(I)) is the Ith value in the */
/*   rearrangement of HX.  IPERM may be applied to another array by */
/*   calling IPPERM, SPPERM, DPPERM or HPPERM. */

/*   An active sort of numerical data is expected to execute somewhat */
/*   more quickly than a passive sort because there is no need to use */
/*   indirect references. But for the character data in HPSORT, integers */
/*   in the IPERM vector are manipulated rather than the strings in HX. */
/*   Moving integers may be enough faster than moving character strings */
/*   to more than offset the penalty of indirect referencing. */

/*   Description of Parameters */
/*      HX - input/output -- array of type character to be sorted. */
/*           For example, to sort a 80 element array of names, */
/*           each of length 6, declare HX as character HX(100)*6. */
/*           If ABS(KFLAG) = 2, then the values in HX will be */
/*           rearranged on output; otherwise, they are unchanged. */
/*      N  - input -- number of values in array HX to be sorted. */
/*      STRBEG - input -- the index of the initial character in */
/*               the string HX that is to be sorted. */
/*      STREND - input -- the index of the final character in */
/*               the string HX that is to be sorted. */
/*      IPERM - output -- permutation array such that IPERM(I) is the */
/*              index of the string in the original order of the */
/*              HX array that is in the Ith location in the sorted */
/*              order. */
/*      KFLAG - input -- control parameter: */
/*            =  2  means return the permutation vector resulting from */
/*                  sorting HX in lexicographical order and sort HX also. */
/*            =  1  means return the permutation vector resulting from */
/*                  sorting HX in lexicographical order and do not sort */
/*                  HX. */
/*            = -1  means return the permutation vector resulting from */
/*                  sorting HX in reverse lexicographical order and do */
/*                  not sort HX. */
/*            = -2  means return the permutation vector resulting from */
/*                  sorting HX in reverse lexicographical order and sort */
/*                  HX also. */
/*      WORK - character variable which must have a length specification */
/*             at least as great as that of HX. */
/*      IER - output -- error indicator: */
/*          =  0  if no error, */
/*          =  1  if N is zero or negative, */
/*          =  2  if KFLAG is not 2, 1, -1, or -2, */
/*          =  3  if work array is not long enough, */
/*          =  4  if string beginning is beyond its end, */
/*          =  5  if string beginning is out-of-range, */
/*          =  6  if string end is out-of-range. */

/*     E X A M P L E  O F  U S E */

/*      CHARACTER*2 HX, W */
/*      INTEGER STRBEG, STREND */
/*      DIMENSION HX(10), IPERM(10) */
/*      DATA (HX(I),I=1,10)/ '05','I ',' I','  ','Rs','9R','R9','89', */
/*     1     ',*','N"'/ */
/*      DATA STRBEG, STREND / 1, 2 / */
/*      CALL HPSORT (HX,10,STRBEG,STREND,IPERM,1,W) */
/*      PRINT 100, (HX(IPERM(I)),I=1,10) */
/* 100 FORMAT (2X, A2) */
/*      STOP */
/*      END */

/* ***REFERENCES  R. C. Singleton, Algorithm 347, An efficient algorithm */
/*                 for sorting with minimal storage, Communications of */
/*                 the ACM, 12, 3 (1969), pp. 185-187. */
/* ***ROUTINES CALLED  XERMSG */
/* ***REVISION HISTORY  (YYMMDD) */
/*   761101  DATE WRITTEN */
/*   761118  Modified by John A. Wisniewski to use the Singleton */
/*           quicksort algorithm. */
/*   811001  Modified by Francis Sullivan for string data. */
/*   850326  Documentation slightly modified by D. Kahaner. */
/*   870423  Modified by Gregory S. Rhoads for passive sorting with the */
/*           option for the rearrangement of the original data. */
/*   890620  Algorithm for rearranging the data vector corrected by R. */
/*           Boisvert. */
/*   890622  Prologue upgraded to Version 4.0 style by D. Lozier. */
/*   920507  Modified by M. McClain to revise prologue text. */
/*   920818  Declarations section rebuilt and code restructured to use */
/*           IF-THEN-ELSE-ENDIF.  (SMR, WRB) */
/* ***END PROLOGUE  HPSORT */
/*     .. Scalar Arguments .. */
/*     .. Array Arguments .. */
/*     .. Local Scalars .. */
/*     .. Local Arrays .. */
/*     .. External Subroutines .. */
/*     .. Intrinsic Functions .. */
/* ***FIRST EXECUTABLE STATEMENT  HPSORT */
    /* Parameter adjustments */
    --iperm;
    hx -= hx_len;

    /* Function Body */
    *ier = 0;
    nn = *n;
    if (nn < 1) {
	*ier = 1;
	xermsg_("SLATEC", "HPSORT", "The number of values to be sorted, N, i"
		"s not positive.", ier, &c__1, (ftnlen)6, (ftnlen)6, (ftnlen)
		54);
	return 0;
    }
    kk = abs(*kflag);
    if (kk != 1 && kk != 2) {
	*ier = 2;
	xermsg_("SLATEC", "HPSORT", "The sort control parameter, KFLAG, is n"
		"ot 2, 1, -1, or -2.", ier, &c__1, (ftnlen)6, (ftnlen)6, (
		ftnlen)58);
	return 0;
    }

    if (i_len(work, work_len) < i_len(hx + hx_len, hx_len)) {
	*ier = 3;
	xermsg_("SLATEC", " HPSORT", "The length of the work variable, WORK,"
		" is too short.", ier, &c__1, (ftnlen)6, (ftnlen)7, (ftnlen)52)
		;
	return 0;
    }
    if (*strbeg > *strend) {
	*ier = 4;
	xermsg_("SLATEC", "HPSORT", "The string beginning, STRBEG, is beyond"
		" its end, STREND.", ier, &c__1, (ftnlen)6, (ftnlen)6, (ftnlen)
		56);
	return 0;
    }
    if (*strbeg < 1 || *strbeg > i_len(hx + hx_len, hx_len)) {
	*ier = 5;
	xermsg_("SLATEC", "HPSORT", "The string beginning, STRBEG, is out-of"
		"-range.", ier, &c__1, (ftnlen)6, (ftnlen)6, (ftnlen)46);
	return 0;
    }
    if (*strend < 1 || *strend > i_len(hx + hx_len, hx_len)) {
	*ier = 6;
	xermsg_("SLATEC", "HPSORT", "The string end, STREND, is out-of-range."
		, ier, &c__1, (ftnlen)6, (ftnlen)6, (ftnlen)40);
	return 0;
    }

/*     Initialize permutation vector */

    i__1 = nn;
    for (i__ = 1; i__ <= i__1; ++i__) {
	iperm[i__] = i__;
/* L10: */
    }

/*     Return if only one value is to be sorted */

    if (nn == 1) {
	return 0;
    }

/*     Sort HX only */

    m = 1;
    i__ = 1;
    j = nn;
    r__ = .375f;

L20:
    if (i__ == j) {
	goto L70;
    }
    if (r__ <= .5898437f) {
	r__ += .0390625f;
    } else {
	r__ += -.21875f;
    }

L30:
    k = i__;

/*     Select a central element of the array and save it in location L */

    ij = i__ + (integer) ((j - i__) * r__);
    lm = iperm[ij];

/*     If first element of array is greater than LM, interchange with LM */

    if (s_cmp(hx + (iperm[i__] * hx_len + (*strbeg - 1)), hx + (lm * hx_len + 
	    (*strbeg - 1)), *strend - (*strbeg - 1), *strend - (*strbeg - 1)) 
	    > 0) {
	iperm[ij] = iperm[i__];
	iperm[i__] = lm;
	lm = iperm[ij];
    }
    l = j;

/*     If last element of array is less than LM, interchange with LM */

    if (s_cmp(hx + (iperm[j] * hx_len + (*strbeg - 1)), hx + (lm * hx_len + (*
	    strbeg - 1)), *strend - (*strbeg - 1), *strend - (*strbeg - 1)) < 
	    0) {
	iperm[ij] = iperm[j];
	iperm[j] = lm;
	lm = iperm[ij];

/*        If first element of array is greater than LM, interchange */
/*        with LM */

	if (s_cmp(hx + (iperm[i__] * hx_len + (*strbeg - 1)), hx + (lm * 
		hx_len + (*strbeg - 1)), *strend - (*strbeg - 1), *strend - (*
		strbeg - 1)) > 0) {
	    iperm[ij] = iperm[i__];
	    iperm[i__] = lm;
	    lm = iperm[ij];
	}
    }
    goto L50;
L40:
    lmt = iperm[l];
    iperm[l] = iperm[k];
    iperm[k] = lmt;

/*     Find an element in the second half of the array which is smaller */
/*     than LM */

L50:
    --l;
    if (s_cmp(hx + (iperm[l] * hx_len + (*strbeg - 1)), hx + (lm * hx_len + (*
	    strbeg - 1)), *strend - (*strbeg - 1), *strend - (*strbeg - 1)) > 
	    0) {
	goto L50;
    }

/*     Find an element in the first half of the array which is greater */
/*     than LM */

L60:
    ++k;
    if (s_cmp(hx + (iperm[k] * hx_len + (*strbeg - 1)), hx + (lm * hx_len + (*
	    strbeg - 1)), *strend - (*strbeg - 1), *strend - (*strbeg - 1)) < 
	    0) {
	goto L60;
    }

/*     Interchange these elements */

    if (k <= l) {
	goto L40;
    }

/*     Save upper and lower subscripts of the array yet to be sorted */

    if (l - i__ > j - k) {
	il[m - 1] = i__;
	iu[m - 1] = l;
	i__ = k;
	++m;
    } else {
	il[m - 1] = k;
	iu[m - 1] = j;
	j = l;
	++m;
    }
    goto L80;

/*     Begin again on another portion of the unsorted array */

L70:
    --m;
    if (m == 0) {
	goto L110;
    }
    i__ = il[m - 1];
    j = iu[m - 1];

L80:
    if (j - i__ >= 1) {
	goto L30;
    }
    if (i__ == 1) {
	goto L20;
    }
    --i__;

L90:
    ++i__;
    if (i__ == j) {
	goto L70;
    }
    lm = iperm[i__ + 1];
    if (s_cmp(hx + (iperm[i__] * hx_len + (*strbeg - 1)), hx + (lm * hx_len + 
	    (*strbeg - 1)), *strend - (*strbeg - 1), *strend - (*strbeg - 1)) 
	    <= 0) {
	goto L90;
    }
    k = i__;

L100:
    iperm[k + 1] = iperm[k];
    --k;

    if (s_cmp(hx + (lm * hx_len + (*strbeg - 1)), hx + (iperm[k] * hx_len + (*
	    strbeg - 1)), *strend - (*strbeg - 1), *strend - (*strbeg - 1)) < 
	    0) {
	goto L100;
    }
    iperm[k + 1] = lm;
    goto L90;

/*     Clean up */

L110:
    if (*kflag <= -1) {

/*        Alter array to get reverse order, if necessary */

	nn2 = nn / 2;
	i__1 = nn2;
	for (i__ = 1; i__ <= i__1; ++i__) {
	    ir = nn - i__ + 1;
	    lm = iperm[i__];
	    iperm[i__] = iperm[ir];
	    iperm[ir] = lm;
/* L120: */
	}
    }

/*     Rearrange the values of HX if desired */

    if (kk == 2) {

/*        Use the IPERM vector as a flag. */
/*        If IPERM(I) < 0, then the I-th value is in correct location */

	i__1 = nn;
	for (istrt = 1; istrt <= i__1; ++istrt) {
	    if (iperm[istrt] >= 0) {
		indx = istrt;
		indx0 = indx;
		s_copy(work, hx + istrt * hx_len, work_len, hx_len);
L130:
		if (iperm[indx] > 0) {
		    s_copy(hx + indx * hx_len, hx + iperm[indx] * hx_len, 
			    hx_len, hx_len);
		    indx0 = indx;
		    iperm[indx] = -iperm[indx];
		    indx = (i__2 = iperm[indx], abs(i__2));
		    goto L130;
		}
		s_copy(hx + indx0 * hx_len, work, hx_len, work_len);
	    }
/* L140: */
	}

/*        Revert the signs of the IPERM values */

	i__1 = nn;
	for (i__ = 1; i__ <= i__1; ++i__) {
	    iperm[i__] = -iperm[i__];
/* L150: */
	}

    }

    return 0;
} /* hpsort_ */

